version: 2.0
jobs:
  build:
    machine:
      image: circleci/classic:latest
    branches:
          only:
            - master
    steps:
      - run:
          name: Install LFTP
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - checkout
      - run:
          name: Send Via SFTP
          command: lftp sftp://studentloanshark-migration:297b09d661cd3e@sftp.pressable.com -e "mirror -v -R --exclude .git/ --exclude .circleci/ ./wp-content/themes; quit"
